import type { DeclarationDetail, DeclarationSummary, PersonTimelineResponse, StatsResponse } from "@/lib/api";

const FIXTURE_PERSON_ID = 424242;

const FIXTURE_DECLARATIONS: DeclarationSummary[] = [
  {
    declaration_id: "e2e-decl-2024",
    user_declarant_id: FIXTURE_PERSON_ID,
    declaration_year: 2024,
    family_members: 1,
    incomes: 2,
    monetary_assets: 2,
    real_estate_rights: 1,
    total_income: "1250000",
    total_assets: "3400000",
    score: 61.4,
    triggered_rules: ["R1_income_assets_mismatch", "R7_cash_heavy"],
    explanation: "Synthetic deterministic fixture for Playwright smoke flow.",
    name: "Smoke Test Person",
    role: "Deputy Director",
    institution: "Argus Test Agency",
    rule_details: [
      {
        rule_name: "R1_income_assets_mismatch",
        score: 34.5,
        triggered: true,
        explanation: "Assets materially exceed declared income.",
      },
      {
        rule_name: "R7_cash_heavy",
        score: 26.9,
        triggered: true,
        explanation: "High share of cash holdings.",
      },
    ],
  },
  {
    declaration_id: "e2e-decl-2023",
    user_declarant_id: FIXTURE_PERSON_ID,
    declaration_year: 2023,
    family_members: 1,
    incomes: 1,
    monetary_assets: 1,
    real_estate_rights: 1,
    total_income: "980000",
    total_assets: "2900000",
    score: 43.2,
    triggered_rules: ["R1_income_assets_mismatch"],
    explanation: "Synthetic deterministic fixture for Playwright smoke flow.",
    name: "Smoke Test Person",
    role: "Department Head",
    institution: "Argus Test Agency",
    rule_details: [
      {
        rule_name: "R1_income_assets_mismatch",
        score: 43.2,
        triggered: true,
        explanation: "Assets materially exceed declared income.",
      },
    ],
  },
];

const FIXTURE_DECLARATION_DETAILS: Record<string, DeclarationDetail> = {
  "e2e-decl-2024": {
    id: "e2e-decl-2024",
    user_declarant_id: FIXTURE_PERSON_ID,
    raw_metadata: {
      year: 2024,
      date: "2025-03-01",
      declaration_type: 1,
    },
    family_members: [
      {
        member_id: "2",
        relation: "Spouse",
        firstname: "Case",
        lastname: "Partner",
        middlename: "",
      },
    ],
    real_estate: [
      {
        object_type: "Apartment",
        total_area: "76.5",
        city: "Kyiv",
        region: "Kyivska",
        district: "Pecherskyi",
        owning_date: "2019",
        cost_assessment: "1800000",
        right_belongs_resolved: "Declarant",
        ownership_type: "Ownership",
        percent_ownership: "100",
      },
    ],
    vehicles: [
      {
        object_type: "Car",
        brand: "Toyota",
        model: "Camry",
        graduation_year: "2020",
        owning_date: "2021",
        cost_date: "650000",
        ownership_type: "Ownership",
        right_belongs_resolved: "Declarant",
      },
    ],
    bank_accounts: [
      {
        institution_name: "State Bank",
        institution_code: "UA0001",
        account_owner_resolved: "Declarant",
      },
    ],
    incomes: [
      {
        person_ref: "1",
        income_type: "Salary",
        amount: "980000",
        source_name: "Argus Test Agency",
      },
      {
        person_ref: "1",
        income_type: "Sale of property",
        amount: "270000",
        source_name: "Private buyer",
      },
    ],
    monetary: [
      {
        person_ref: "1",
        asset_type: "Cash",
        currency_raw: "UAH",
        currency_code: "UAH",
        amount: "500000",
        organization: "",
        organization_status: "declared",
        ownership_type: "Ownership",
      },
      {
        person_ref: "1",
        asset_type: "Bank deposit",
        currency_raw: "UAH",
        currency_code: "UAH",
        amount: "1100000",
        organization: "State Bank",
        organization_status: "declared",
        ownership_type: "Ownership",
      },
    ],
    summary: FIXTURE_DECLARATIONS[0],
    bio: {
      firstname: "Smoke",
      middlename: "Flow",
      lastname: "Person",
      work_post: "Deputy Director",
      work_place: "Argus Test Agency",
    },
  },
  "e2e-decl-2023": {
    id: "e2e-decl-2023",
    user_declarant_id: FIXTURE_PERSON_ID,
    raw_metadata: {
      year: 2023,
      date: "2024-03-02",
      declaration_type: 1,
    },
    family_members: [
      {
        member_id: "2",
        relation: "Spouse",
        firstname: "Case",
        lastname: "Partner",
        middlename: "",
      },
    ],
    real_estate: [],
    vehicles: [],
    bank_accounts: [],
    incomes: [
      {
        person_ref: "1",
        income_type: "Salary",
        amount: "980000",
        source_name: "Argus Test Agency",
      },
    ],
    monetary: [
      {
        person_ref: "1",
        asset_type: "Cash",
        currency_raw: "UAH",
        currency_code: "UAH",
        amount: "420000",
        organization: "",
        organization_status: "declared",
        ownership_type: "Ownership",
      },
    ],
    summary: FIXTURE_DECLARATIONS[1],
    bio: {
      firstname: "Smoke",
      middlename: "Flow",
      lastname: "Person",
      work_post: "Department Head",
      work_place: "Argus Test Agency",
    },
  },
};

const FIXTURE_PERSON_TIMELINE: PersonTimelineResponse = {
  user_declarant_id: FIXTURE_PERSON_ID,
  name: "Smoke Flow Person",
  snapshot_count: 2,
  snapshots: [
    {
      declaration_id: "e2e-decl-2023",
      declaration_year: 2023,
      declaration_type: 1,
      total_income: "980000",
      total_monetary: "1700000",
      total_real_estate: "1200000",
      total_assets: "2900000",
      cash: "420000",
      bank: "1280000",
      unknown_share: 0.05,
      income_count: 1,
      monetary_count: 1,
      real_estate_count: 1,
      vehicle_count: 0,
      role: "Department Head",
      institution: "Argus Test Agency",
    },
    {
      declaration_id: "e2e-decl-2024",
      declaration_year: 2024,
      declaration_type: 1,
      total_income: "1250000",
      total_monetary: "1900000",
      total_real_estate: "1500000",
      total_assets: "3400000",
      cash: "500000",
      bank: "1400000",
      unknown_share: 0.03,
      income_count: 2,
      monetary_count: 2,
      real_estate_count: 1,
      vehicle_count: 1,
      role: "Deputy Director",
      institution: "Argus Test Agency",
    },
  ],
  changes: [
    {
      from_year: 2023,
      to_year: 2024,
      income_prev: "980000",
      income_curr: "1250000",
      income_delta: "270000",
      income_ratio: 1.2755,
      income_growth: 0.2755,
      monetary_prev: "1700000",
      monetary_curr: "1900000",
      monetary_delta: "200000",
      monetary_ratio: 1.1176,
      assets_prev: "2900000",
      assets_curr: "3400000",
      asset_growth: 0.1724,
      cash_prev: "420000",
      cash_curr: "500000",
      cash_delta: "80000",
      unknown_share_prev: 0.05,
      unknown_share_curr: 0.03,
      unknown_share_delta: -0.02,
      role_prev: "Department Head",
      role_curr: "Deputy Director",
      role_changed: true,
      major_assets_appeared: 1,
      major_assets_disappeared: 0,
      max_appeared_value: "650000",
      max_disappeared_value: null,
      one_off_income_curr: "270000",
    },
  ],
  timeline_score: {
    total_score: 38.7,
    triggered_rules: ["CR14_major_asset_changes"],
    explanation: "Deterministic fixture timeline used in smoke tests.",
    rule_details: [
      {
        rule_name: "CR14_major_asset_changes",
        score: 38.7,
        triggered: true,
        explanation: "Major one-year asset movement.",
      },
    ],
  },
};

export const E2E_FIXTURE_DATA = {
  stats: {
    total_declarations: FIXTURE_DECLARATIONS.length,
    flagged_declarations: FIXTURE_DECLARATIONS.filter((item) => item.score > 0).length,
    average_score: 52.3,
    rule_distribution: {
      R1_income_assets_mismatch: 2,
      R7_cash_heavy: 1,
      CR14_major_asset_changes: 1,
    },
  } satisfies StatsResponse,
  declarations: FIXTURE_DECLARATIONS,
  declarationDetails: FIXTURE_DECLARATION_DETAILS,
  personTimeline: FIXTURE_PERSON_TIMELINE,
};
